// Generated by scripts/build_airports.py — do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::airports {

struct Airport {
  char ident[5];
  int32_t lat_e7;
  int32_t lon_e7;
};

/** Runways are grouped by airport_idx and sorted longest-first. */
struct Runway {
  uint16_t airport_idx;
  int32_t le_lat_e7;
  int32_t le_lon_e7;
  int32_t he_lat_e7;
  int32_t he_lon_e7;
  uint16_t length_m;
  char le_ident[5];
  char he_ident[5];
};

constexpr size_t kAirportCount = 4199;
constexpr size_t kRunwayCount = 6067;

extern const Airport kAirports[];
extern const Runway kRunways[];

}  // namespace data::airports
